### ISSUE TITLE
Epic 1: Account System with User Login and Authentication

### ISSUE THREAD

**Issue by AnoldGH** [jaden-yejun-lee/MuseGuesser#1]
## Epic
As an user, I want to be able to securely login and have my account information stored so I can log back into my account and have my data saved

## User Stories
- [x] As an user, I want to be able to create my own profile
  - [x] Frontend signup component
  - [x] Send the request to the server for verification & check if already existent
  - [x] Store profiles in the database
- [x] As an user, I want to be able to log back into my account whenever I want
  - [x] Frontend login component
  - [x] Backend verification
  - [x] (Enhancement) Secure password transmission, salting
- [x] As an user, I want to be able to view my past history of games and correlated statistics
  - [x] #38
  - [x] Frontend component for profile statistics / history
