### ISSUE TITLE
Epic 0: Create Application

### ISSUE THREAD

**Issue by jaden-yejun-lee** [jaden-yejun-lee/MuseGuesser#10]
## Epic
Figure out tech stack and implement basic structure of frontend/backend

## User Stories
- [x] Agree on tech stack
- [x] Implement basic frontend
- [x] Implement basic backend
