### ISSUE TITLE
Epic 3: Main Gameplay

### ISSUE THREAD

**Issue by Hakob3215** [jaden-yejun-lee/MuseGuesser#4]
## Epic
As a user, I want to be able play a round of a game where I answer multiple choice questions centered around a certain song / artist.

## User Stories
- [x] As a player, I want to be able to have a music genre chosen for the type of questions.
  - [x] Implement a genre-picking component in the frontend  
- [x] As a player, I want to be able to answer questions surround certain songs / artists.
  - [x] #35
  - [x] #34
  - [x] #33
  - [x] #37
- [x] As a player, I want to be able to listen / hear the current song.
  - [x] Implement a simple music player
  - [x] #23
  - [x] #29
