### ISSUE TITLE
Epic 5: Spotify Proxy and Authorization Handler

### ISSUE THREAD

**Issue by AnoldGH** [jaden-yejun-lee/MuseGuesser#9]
## Epic
High-level managers and proxys handling Spotify authorization / requests / rate limits / cachings.

## User Stories
- [x] As a user, I want every track retrieval to be fast
  - [x] Implement a server-side in-memory caching (with #13 )
  - [x] Handles token expiration (with commit 8f8203d)
- [x] As a user, I want to be hidden from all trivia handling Spotify services
  - [x] Rate limit monitoring (with #13)
  - [x] Get access token from Spotify (with commit 313b31b)
- [x] As a user, I want to be prompted question sets with minimal data transfer
  - [x] #26
  - [x] #27
  - [x] #28
